#!/bin/bash
cd /var/www/html
apt update && apt upgrade -y
apt install openssh-server sudo -y

apt install -qq -y --no-install-recommends wget && rm -rf /var/lib/apt/lists/* &&  \
    wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar &&  \
    apt-get purge -y --auto-remove wget
    
php wp-cli.phar --info
chmod +x wp-cli.phar
mv wp-cli.phar /usr/local/bin/wp
wp --info
